clinic_front:
    resource: "@ClinicFrontBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

