<?php

namespace Clinic\FrontBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends EntityRepository
{

    /**
     * @param Brand $brand
     * @return array
     */
    public function getCategoriesByBrand(Brand $brand, $published = true)
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin('c.products', 'p')
            ->leftJoin('p.brand', 'b')
            ->andWhere('p.published = :published')
            ->andWhere('b.id = :brandID')
            ->setParameters(array("brandID"=> $brand->getId(), "published" => $published))
            ->getQuery();

        return $query->getResult();
    }

}
