<?php

namespace Clinic\FrontBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @param Category $category
     * @return array
     */
    public function getPublished()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.created', 'DESC')
            ->andWhere('p.published = true')
            ->getQuery();

        return $query->getResult();
    }


}
